name: 🔍 PR Title Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-title:
    name: Validate PR Title Format
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title format
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Allowed types (customize for your project)
          types: |
            feat
            fix
            docs
            refactor
            chore
            test
            ci
          # Optionally enforce a scope, e.g. "gateway", "recipe", etc.
          requireScope: false
          # Example title format: feat(gateway): add jwt validation
          subjectPattern: .+
          subjectPatternError: "❌ The PR title must include a subject after the type and scope."

      - name: PR title valid
        if: ${{ success() }}
        run: echo "✅ PR title format looks good!"
